package sakila.entity;
// Generated 09/12/2015 10:10:53 by Hibernate Tools 4.3.1


import java.io.Serializable;

/**
 * Organizador generated by hbm2java
 */
public class Organizador  implements java.io.Serializable {


     private String siape;
     private Serializable nomeorg;
     private Serializable cpforg;
     private Serializable senhaorg;

    public Organizador() {
    }

	
    public Organizador(String siape) {
        this.siape = siape;
    }
    public Organizador(String siape, Serializable nomeorg, Serializable cpforg, Serializable senhaorg) {
       this.siape = siape;
       this.nomeorg = nomeorg;
       this.cpforg = cpforg;
       this.senhaorg = senhaorg;
    }
   
    public String getSiape() {
        return this.siape;
    }
    
    public void setSiape(String siape) {
        this.siape = siape;
    }
    public Serializable getNomeorg() {
        return this.nomeorg;
    }
    
    public void setNomeorg(Serializable nomeorg) {
        this.nomeorg = nomeorg;
    }
    public Serializable getCpforg() {
        return this.cpforg;
    }
    
    public void setCpforg(Serializable cpforg) {
        this.cpforg = cpforg;
    }
    public Serializable getSenhaorg() {
        return this.senhaorg;
    }
    
    public void setSenhaorg(Serializable senhaorg) {
        this.senhaorg = senhaorg;
    }




}


